@startuml

title Account Domain - Class Diagram

folder Entities {
  class UserEntity
  class CategoryEntity
  class WalletEntity
  class WalletGroupEntity
}

folder Repositories {
  class WalletRepository
  
  class CategoryRepository
}

folder Services {
  class getWalletsByGroupService
  
  class getCategoriesService
  
  folder Category {
    class getService
    class setService
    class delService
    class addService
  }
  
  folder Wallet {
    class getService.
    class setService.
    class delService.
    class addService.
  }
  
  folder WalletGroup {
    class getService_
    class setService_
    class delService_
    class addService_
  }
}

@enduml