@startuml

title Operations Domain - Class Diagram

folder Entities {
  class CategoryEntity
  class WalletEntity
  class OperationEntity
}

folder Repositories {
  class OperationRepository
}

folder Services {
  class getOperationsService
  class getOperationService
  class setOperationService
  class delOperationService
  class addOperationService
  class importOperationService
}

interface IImport

@enduml