@startuml

title Reports Domain - Class Diagram

folder Entities {
  class CategoryEntity
  class WalletEntity
}

folder Repositories {
  class ReportsRepository
}

folder Services {
  class getWalletsReportService
  class getCategoriesReportService
}

@enduml